"""add financial facts

Revision ID: 36134e0d3560
Revises: e4dda2eedbb0
Create Date: 2026-10-03 13:54:22.904569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36134e0d3560'
down_revision: Union[str, Sequence[str], None] = 'e4dda2eedbb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_facts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_cik', sa.String(length=10), nullable=False),
    sa.Column('metric', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Numeric(precision=24, scale=4), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('period_type', sa.String(length=20), nullable=True),
    sa.Column('fiscal_year', sa.Integer(), nullable=True),
    sa.Column('fiscal_period', sa.String(length=10), nullable=True),
    sa.Column('form', sa.String(length=20), nullable=True),
    sa.Column('filed', sa.Date(), nullable=True),
    sa.Column('accession_number', sa.String(length=30), nullable=True),
    sa.Column('frame', sa.String(length=30), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_facts_company_cik'), 'financial_facts', ['company_cik'], unique=False)
    op.create_index('ix_financial_facts_company_metric_period', 'financial_facts', ['company_cik', 'metric', 'period_end'], unique=False)
    op.create_index(op.f('ix_financial_facts_metric'), 'financial_facts', ['metric'], unique=False)
    op.create_index(op.f('ix_financial_facts_period_end'), 'financial_facts', ['period_end'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_financial_facts_period_end'), table_name='financial_facts')
    op.drop_index(op.f('ix_financial_facts_metric'), table_name='financial_facts')
    op.drop_index('ix_financial_facts_company_metric_period', table_name='financial_facts')
    op.drop_index(op.f('ix_financial_facts_company_cik'), table_name='financial_facts')
    op.drop_table('financial_facts')
    # ### end Alembic commands ###
