"""add filing chunks

Revision ID: 77068e51af12
Revises: 36134e0d3560
Create Date: 2026-10-03 18:15:21.344117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77068e51af12'
down_revision: Union[str, Sequence[str], None] = '36134e0d3560'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filing_chunks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_cik', sa.String(length=10), nullable=False),
    sa.Column('accession_number', sa.String(length=30), nullable=False),
    sa.Column('form', sa.String(length=20), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('filed', sa.Date(), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_id', sa.String(length=50), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('start_char', sa.Integer(), nullable=False),
    sa.Column('end_char', sa.Integer(), nullable=False),
    sa.Column('sec_url', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_filing_chunks_accession_index', 'filing_chunks', ['accession_number', 'chunk_index'], unique=True)
    op.create_index(op.f('ix_filing_chunks_accession_number'), 'filing_chunks', ['accession_number'], unique=False)
    op.create_index('ix_filing_chunks_company_accession', 'filing_chunks', ['company_cik', 'accession_number'], unique=False)
    op.create_index(op.f('ix_filing_chunks_company_cik'), 'filing_chunks', ['company_cik'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_filing_chunks_company_cik'), table_name='filing_chunks')
    op.drop_index('ix_filing_chunks_company_accession', table_name='filing_chunks')
    op.drop_index(op.f('ix_filing_chunks_accession_number'), table_name='filing_chunks')
    op.drop_index('ix_filing_chunks_accession_index', table_name='filing_chunks')
    op.drop_table('filing_chunks')
    # ### end Alembic commands ###
