"""add refresh state attempts and filing publication

Revision ID: f94c6f41e0cb
Revises: d7b834408ba8
Create Date: 2026-10-08 18:02:38.421762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f94c6f41e0cb'
down_revision: Union[str, Sequence[str], None] = 'd7b834408ba8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_refresh_state',
    sa.Column('company_cik', sa.String(length=10), nullable=False),
    sa.Column('data_version', sa.BigInteger(), nullable=False),
    sa.Column('facts_version', sa.BigInteger(), nullable=False),
    sa.Column('evidence_version', sa.BigInteger(), nullable=False),
    sa.Column('facts', sa.JSON(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.CheckConstraint('data_version >= 0 AND facts_version >= 0 AND evidence_version >= 0 AND facts_version <= data_version AND evidence_version <= data_version', name='ck_refresh_versions'),
    sa.ForeignKeyConstraint(['company_cik'], ['companies.cik'], ),
    sa.PrimaryKeyConstraint('company_cik')
    )
    op.create_table('filing_publications',
    sa.Column('company_cik', sa.String(length=10), nullable=False),
    sa.Column('accession_number', sa.String(length=30), nullable=False),
    sa.Column('form', sa.String(length=20), nullable=False),
    sa.Column('filed', sa.Date(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('content_digest', sa.String(length=64), nullable=False),
    sa.Column('cleaned_text', sa.Text(), nullable=True),
    sa.Column('configuration', sa.String(length=200), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_version', sa.BigInteger(), nullable=False),
    sa.CheckConstraint('chunk_count > 0 AND data_version >= 0', name='ck_publication_counts'),
    sa.ForeignKeyConstraint(['company_cik'], ['companies.cik'], ),
    sa.PrimaryKeyConstraint('company_cik', 'accession_number')
    )
    op.create_table('refresh_attempts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('company_cik', sa.String(length=10), nullable=False),
    sa.Column('stream', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_version', sa.BigInteger(), nullable=True),
    sa.Column('source_digest', sa.String(length=64), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.CheckConstraint("published_version IS NULL OR (published_version > 0 AND status IN ('updated', 'pending'))", name='ck_refresh_event_version'),
    sa.CheckConstraint("status IN ('running', 'updated', 'no_change', 'pending', 'failed', 'interrupted')", name='ck_refresh_attempt_status'),
    sa.CheckConstraint("stream IN ('facts', 'evidence')", name='ck_refresh_stream'),
    sa.ForeignKeyConstraint(['company_cik'], ['companies.cik'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_cik', 'published_version', name='uq_refresh_committed_version')
    )
    op.create_index(op.f('ix_refresh_attempts_company_cik'), 'refresh_attempts', ['company_cik'], unique=False)
    op.create_index(op.f('ix_refresh_attempts_run_id'), 'refresh_attempts', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refresh_attempts_run_id'), table_name='refresh_attempts')
    op.drop_index(op.f('ix_refresh_attempts_company_cik'), table_name='refresh_attempts')
    op.drop_table('refresh_attempts')
    op.drop_table('filing_publications')
    op.drop_table('company_refresh_state')
    # ### end Alembic commands ###
