import type { ResearchAnswer } from "./finlens-api";

// Display matching only: never selects a fact, validates a claim or ranks sources.
type Span = { start: number; end: number; kind: "term" | "value" };
export type Excerpt = { text: string; start: number; end: number; parts: { text: string; kind: Span["kind"] | null }[] };
const ALIASES: Record<string, string[]> = {
  revenue: ["total net sales", "net sales", "revenue"], net_income: ["net income"],
  gross_profit: ["gross profit"], operating_income: ["operating income"], diluted_eps: ["diluted earnings per share", "earnings per share"],
  cash_and_equivalents: ["cash and cash equivalents"], total_assets: ["total assets"], total_liabilities: ["total liabilities"],
  operating_cash_flow: ["cash generated by operating activities", "operating cash flow"], capital_expenditures: ["property, plant and equipment", "capital expenditure"],
  free_cash_flow: ["free cash flow"], revenue_growth_yoy: ["net sales", "revenue", "year-over-year"],
  gross_margin: ["gross margin"], operating_margin: ["operating margin"], net_margin: ["net margin"],
};
const STOP = new Set("how much what was were is are does did do the a an of for to in on and or with from its apple apples company report reported reporting latest available quarter quarterly annual year fiscal ended main please tell me".split(" "));
const METHOD = /\b(?:accounting|polic(?:y|ies)|method|recogniz\w*)\b|\bhow\b(?!\s+much\b)[^?]{0,100}\b(?:report(?:ed|ing)?|recogniz\w*)\b/i;
const METHOD_PHRASES = /\b(?:revenue\s+(?:is\s+)?recognized|recogniz\w*|performance obligations?|control|disaggregated net sales|accounting policies|basis of presentation|generally accepted accounting principles|deferred revenue)\b/gi;
const SCALE: Record<string, number> = { thousand: 3, million: 6, billion: 9, trillion: 12 };
const escape = (value: string) => value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");

// Compare decimal strings exactly (including negative/zero), never rounded display values.
function decimal(value: string, power = 0): string | null {
  const parsed = /^(-?)(\d+)(?:\.(\d+))?$/.exec(value.replaceAll(",", ""));
  if (!parsed) return null;
  const fraction = parsed[3] ?? "";
  let digits = (parsed[2] + fraction).replace(/^0+/, "") || "0";
  let exponent = power - fraction.length;
  while (digits.endsWith("0") && digits !== "0") { digits = digits.slice(0, -1); exponent++; }
  return digits === "0" ? "0" : `${parsed[1]}${digits}e${exponent}`;
}

function terms(query: string, answer?: ResearchAnswer | null): string[] {
  const words = query.toLowerCase().match(/[a-z][a-z-]+/g) ?? [];
  const aliases = answer?.matched ? ALIASES[answer.metric ?? ""] ?? [] : [];
  // Common metric phrases are presentation synonyms, not an intent recognizer.
  const phrases = Object.values(ALIASES).flat().filter(phrase => query.toLowerCase().includes(phrase));
  if (/\brevenue\b/i.test(query)) phrases.push(...ALIASES.revenue);
  for (const phrase of ["supply constraints", "services revenue", "artificial intelligence"]) if (query.toLowerCase().includes(phrase)) phrases.push(phrase);
  const matchedPhrases = [...aliases, ...phrases];
  return [...new Set([...matchedPhrases, ...words.filter(word => word.length > 2 && !STOP.has(word)
    && !matchedPhrases.some(phrase => phrase.includes(" ") && phrase.split(" ").includes(word)))])].sort((a, b) => b.length - a.length).slice(0, 16);
}

function termSpans(text: string, query: string, answer?: ResearchAnswer | null): Span[] {
  const spans: Span[] = [];
  for (const term of terms(query, answer)) {
    for (const match of text.matchAll(new RegExp(`\\b${escape(term)}\\b`, "gi"))) {
      spans.push({ start: match.index!, end: match.index! + match[0].length, kind: "term" });
    }
  }
  if (METHOD.test(query)) for (const match of text.matchAll(METHOD_PHRASES)) {
    spans.push({ start: match.index!, end: match.index! + match[0].length, kind: "term" });
  }
  return spans;
}

function localScale(text: string, index: number): number | null {
  // Only a preceding nearby table declaration, before any new note/page/per-share
  // boundary. A unit label later in the passage cannot scale an earlier number.
  const prefix = text.slice(Math.max(0, index - 900), index);
  const declarations = [...prefix.matchAll(/\((?:dollars\s+)?in\s+(thousands|millions|billions)\)/gi)];
  const last = declarations.at(-1);
  if (!last) return null;
  const between = prefix.slice(last.index! + last[0].length);
  if (/\bNote\s+\d|Form\s+10-[QK]|per share|shares in/i.test(between)) return null;
  return SCALE[last[1].toLowerCase().replace(/s$/, "")];
}

function valueSpans(text: string, answer: ResearchAnswer | null | undefined, peers: string[]): Span[] {
  const point = answer?.observation;
  if (!answer?.matched || answer.status !== "available" || point?.value == null) return [];
  // Selected-filing excerpts do not establish a historical comparison's period
  // alignment. Exact financial proof lives in its structured provenance.
  if (answer.answer_kind && answer.answer_kind !== "latest_metric") return [];
  const target = decimal(point.value);
  if (target === null) return [];
  const spans: Span[] = [];
  // Currency requires $, %, or explicit per-share wording; unlabelled integers
  // are deliberately not interpreted as dollar amounts.
  // Consume the whole notation before interpreting it. Matching an interior $
  // would discard a foreign currency prefix or an accounting/leading sign.
  const pattern = /(?<![\w$()+−-])(?:\(\s*)?(?:[-+−]+\s*)?(?:(?:[a-z]{1,5})?\$\s*(?:[-+−]+\s*)?\d[\d,]*(?:\.\d+)?|\d[\d,]*(?:\.\d+)?\s*%)(?:\s*(?:thousand|million|billion|trillion)\b)?(?:\s*\))?(?:\s*(?:thousand|million|billion|trillion)\b)?/gi;
  for (const match of text.matchAll(pattern)) {
    const raw = match[0], index = match.index!;
    const prefix = text.slice(0, index).trimEnd();
    // Reject unsupported detached signs/currency prefixes rather than retrying
    // at a positive interior token. Uppercase short codes include C, A and CAD.
    if (/[\p{Sc}($+−-]$/u.test(prefix) || /\b[A-Z]{1,3}$/.test(prefix)
      || /\b(?:CAD|AUD|NZD|HKD|SGD|C|A)\s*$/i.test(prefix)) continue;
    const parsed = /^(\(\s*)?([-−]?\s*)([a-z]*)(\$)?\s*([-−]?\s*)(\d[\d,]*(?:\.\d+)?)(\s*%)?(?:\s*(thousand|million|billion|trillion)\b)?(\s*\))?(?:\s*(thousand|million|billion|trillion)\b)?$/i.exec(raw);
    if (!parsed) continue;
    const [, opening, before, currencyPrefix, dollar, after, number, percent, innerScale, closing, outerScale] = parsed;
    const signs = [before.trim(), after.trim()].filter(Boolean);
    if (Boolean(opening) !== Boolean(closing) || signs.length > 1 || (opening && signs.length)
      || currencyPrefix || (innerScale && outerScale) || (percent && (dollar || innerScale || outerScale))) continue;
    const signed = `${opening || signs.length ? "-" : ""}${number}`;
    let power: number | null = null;
    if (point.unit === "ratio" && percent) power = -2;
    if (point.unit === "USD" && dollar) {
      const suffix = (innerScale || outerScale)?.toLowerCase();
      power = suffix ? SCALE[suffix] : localScale(text, index);
      // Overlap chunks can omit a table header. Transfer a declaration only for
      // the same exact row fragment in another supplied passage, never globally.
      if (power === null && !suffix) {
        const row = text.slice(Math.max(0, index - 32), index + raw.length);
        const scales = peers.flatMap(peer => {
          const found: number[] = [];
          for (let at = peer.indexOf(row); at >= 0; at = peer.indexOf(row, at + row.length)) {
            const scale = localScale(peer, at + row.length - raw.length);
            if (scale !== null) found.push(scale);
          }
          return found;
        });
        if (scales.length && scales.every(scale => scale === scales[0])) power = scales[0];
      }
      // Exact full-dollar values are safe only with an explicit dollars label.
      if (power === null && /\b(?:in dollars|USD)\s*:?\s*$/i.test(text.slice(Math.max(0, index - 60), index))) power = 0;
    }
    if (point.unit === "USD/share" && dollar && !innerScale && !outerScale && /(?:earnings|income) per share/i.test(text.slice(Math.max(0, index - 70), index))) power = 0;
    if (power !== null && decimal(signed, power) === target) spans.push({ start: index, end: index + raw.length, kind: "value" });
  }
  return spans;
}

export function evidenceExcerpt(text: string, query: string, answer?: ResearchAnswer | null, peers: string[] = []): Excerpt {
  const spans = [...termSpans(text, query, answer), ...valueSpans(text, answer, peers)];
  const method = METHOD.test(query);
  // Evaluate bounded windows anchored on matches. No scores leave this helper;
  // passage order and evidence status are owned by the backend.
  let start = 0, end = Math.min(text.length, 280), best = -1;
  for (const anchor of spans.slice(0, 200)) {
    const nearbyValue = !method ? spans.find(span => span.kind === "value" && Math.abs(span.start - anchor.start) < 60) : undefined;
    let left = Math.max(0, anchor.start - 70);
    const sentence = text.lastIndexOf(". ", anchor.start);
    if (sentence >= left) left = sentence + 2;
    else { const word = text.indexOf(" ", left); if (left > 0 && word < anchor.start) left = word + 1; }
    if (nearbyValue) {
      const rowLabel = spans.filter(span => span.kind === "term" && span.end <= nearbyValue.start && nearbyValue.start - span.start < 60)
        .sort((a, b) => b.end - a.end || a.start - b.start)[0];
      left = rowLabel?.start ?? Math.max(0, nearbyValue.start - 30);
    }
    let right = Math.min(text.length, left + (nearbyValue ? 200 : 280));
    const sentenceEnd = text.indexOf(". ", anchor.end);
    if (sentenceEnd >= anchor.end && sentenceEnd < right) right = sentenceEnd + 1;
    else if (right < text.length) { const word = text.lastIndexOf(" ", right); if (word > anchor.end) right = word; }
    const window = text.slice(left, right);
    const distinct = new Set(spans.filter(span => span.start >= left && span.end <= right).map(span => text.slice(span.start, span.end).toLowerCase()));
    const methodWeight = [...window.matchAll(METHOD_PHRASES)].reduce((sum, match) => sum +
      (/recogniz|performance obligations|disaggregated net sales|generally accepted/i.test(match[0]) ? 8 : /deferred revenue/i.test(match[0]) ? 4 : 2), 0);
    const score = distinct.size + (method ? methodWeight : spans.some(span => span.kind === "value" && span.start >= left && span.end <= right) ? 20 : 0);
    if (score > best) { best = score; start = left; end = right; }
  }
  const selected = spans.filter(span => span.start >= start && span.end <= end).sort((a, b) => a.start - b.start || (a.kind === b.kind ? b.end - a.end : a.kind === "value" ? -1 : 1));
  const parts: Excerpt["parts"] = [];
  let cursor = start;
  // Cap repeated generic marks. Value matches always take precedence over terms.
  const seen = new Set<string>();
  for (const span of selected) {
    if (span.start < cursor) continue;
    const key = text.slice(span.start, span.end).toLowerCase();
    if (span.kind === "term" && seen.has(key)) continue;
    if (span.start > cursor) parts.push({ text: text.slice(cursor, span.start), kind: null });
    parts.push({ text: text.slice(span.start, span.end), kind: span.kind });
    seen.add(key); cursor = span.end;
  }
  if (cursor < end) parts.push({ text: text.slice(cursor, end), kind: null });
  return { text: text.slice(start, end), start, end, parts };
}
